Memgraph platform
memgraph/helm-charts pull request #13
Opened 2024-01-24 00:58 UTC by tewnut

2024-01-24 11:19 UTC, antejavor commented
Hi @tewnut, thanks a lot for opening a PR 🚀 . I will look into this in the next few days!

2024-01-29 15:04 UTC, CarlEkerot commented on charts/memgraph-platform/README.md
> +| `nodeSelector`                               | Node selector for pods                                      | `{}`                        |
`nodeSelector`, `tolerations` and `affinity` doesn't seem to be used in the chart.

2024-02-07 08:36 UTC, CarlEkerot commented
Been using this somewhat successfully the last week or so. I am not knowledgeable enough in Helm charts to give a proper review, but here are some pointers as a user:

* Deploying this from IaC, it would be nice to (optionally) provide existing volume claims for storage
* I didn't manage to get the ingress to work properly. Haven't spent too much time debugging the issue.
* See review comment regarding `nodeSelector`, `tolerations` and `affinity`

2024-02-08 10:21 UTC, karmenrabar commented
Hello @CarlEkerot, thanks so much for the review! @antejavor is currently on his AL, but he'll get back to you as soon as he's back. I'm glad to hear that it's going successfully for you. Could you tell us what you are working on? :)

2024-02-08 12:23 UTC, CarlEkerot commented
> Hello @CarlEkerot, thanks so much for the review! @antejavor is currently on his AL, but he'll get back to you as soon as he's back. I'm glad to hear that it's going successfully for you. Could you tell us what you are working on? :)

Mostly poking around with memgraph and a few other graph DBs :) Looking forward to using this chart once it's in a stable state :+1:

2024-02-09 09:09 UTC, karmenrabar commented
Nice to hear that you're exploring Memgraph, @CarlEkerot  :) Feel free to ask if you have more questions, and don't hesitate to reach out on our [discord](https://discord.com/invite/memgraph) or book an [office hours call ](https://calendly.com/d/3jv-347-54b/memgraph-office-hours)!

2024-02-14 05:15 UTC, tewnut commented
> Been using this somewhat successfully the last week or so. I am not knowledgeable enough in Helm charts to give a proper review, but here are some pointers as a user:
> 
> * Deploying this from IaC, it would be nice to (optionally) provide existing volume claims for storage
> * I didn't manage to get the ingress to work properly. Haven't spent too much time debugging the issue.
> * See review comment regarding `nodeSelector`, `tolerations` and `affinity`

can you share the ingress section of your values.yaml file?

2024-02-23 15:25 UTC, katarinasupe commented
Hi @tewnut, thank you so much for providing the chart for the Memgraph Platform. With the Memgraph Lab image being available on the Docker hub now, we have been working on a new way of running the Memgraph Platform that should ease the deployment process, and that's why we still need to review this. With Memgraph 2.15, we will make these changes public, and then we'll see what to do with Helm Charts (how to approach the Memgraph Platform deployment properly). 

@CarlEkerot thank you for the review as well! 👏  Stay tuned for the updates 😄

2024-02-24 03:14 UTC, tewnut commented
> Hi @tewnut, thank you so much for providing the chart for the Memgraph Platform. With the Memgraph Lab image being available on the Docker hub now, we have been working on a new way of running the Memgraph Platform that should ease the deployment process, and that's why we still need to review this. With Memgraph 2.15, we will make these changes public, and then we'll see what to do with Helm Charts (how to approach the Memgraph Platform deployment properly).
> 
> @CarlEkerot thank you for the review as well! 👏 Stay tuned for the updates 😄

Thanks, looking forward to the new release...

2024-04-25 14:25 UTC, antejavor requested changes
Hi @tewnut,


First of all, thanks for the contribution and effort. 🚀 

As @katarinasupe [has said previously](https://github.com/memgraph/helm-charts/pull/13#issuecomment-1961529626) and 
as you can read in [release notes](https://memgraph.com/docs/release-notes#transition-to-multi-container-memgraph-platform-from-version-215), we have changed how Memgraph platform works. 

Now, it is a Docker compose (based on the [Memgraph mage](https://hub.docker.com/r/memgraph/memgraph-mage/tags) and [Memgraph lab](https://hub.docker.com/r/memgraph/lab). Those are two separate containers now; there is no longer a single container image that has both products. 

Unfortunately, this means this chart is not valid. Approximately three months ago, when you opened PR, we started planning the transition to the new platform. Due to upcoming changes and other priorities, this PR didn't receive proper attention. 

As you can see in our [roadmap](https://github.com/memgraph/roadmap), we started working on improving our Kubernetes experience, and this repository will receive more changes and updates in the following weeks. 

One of the updates is to create the helm charts for replication and high-availability support.  

This will be my main focus, and having a platform chart would be a great addition to this repository. 

The question is, are you willing to adopt this chart to base the deployment on the two images (mage and lab) so we can wrap up and merge this PR?

2024-04-25 15:32 UTC, tewnut commented
Yeah, I think this is altogether better approach. Thanks for the update. 

Let me try creating the charts for my k8s cluster. When things are in good shape, I will create a PR in this repo, should be a couple of days...

2024-04-26 11:58 UTC, antejavor commented
> Yeah, I think this is a better approach altogether. Thanks for the update.
> 
> Let me try creating the charts for my k8s cluster. When things are in good shape, I will create a PR in this repo, should be a couple of days...

Keep in mind we updated the contribution guide a bit: https://github.com/memgraph/helm-charts/commit/c1cc60603a8ea2f3572e5f5685190b65b60b7c7b 

If you are going to create a new PR, please use the latest release branch and create a PR on a specific release branch. 

If you are going to use this PR it is also fine.

2024-05-03 09:49 UTC, antejavor commented
Hi @tewnut can we close this PR now?

2024-05-04 10:11 UTC, closed without merging