Add support for mounting custom query modules
memgraph/helm-charts pull request #67
Opened 2024-10-28 09:12 UTC by matkob

Closes #66

2024-11-04 11:38 UTC, antejavor requested changes
Hi @matkob thanks a lot  for this contribution. 🚀  Let's just fix the empty space, so we can re-run the test.

If I understood correctly, you would have something like this: 

values.yaml
``` 
customQueryModules:
  - volume: "module-volume-1"
    file: "module1.py"
  - volume: "module-volume-2"
    file: "module2.py"
```
Template:
```
- name: "module-volume-1"
  mountPath: "/var/lib/memgraph/internal_modules/module1.py"
  subPath: "module1.py"
- name: "module-volume-2"
  mountPath: "/var/lib/memgraph/internal_modules/module2.py"
  subPath: "module2.py"
```

We obviously do not have a clear way of adding this,  except maybe [user defined volume here](https://github.com/memgraph/helm-charts/blob/main/charts/memgraph/templates/statefulset.yaml#L185-L188). 

I am curious if you can comment on what is the benefit of having a volume per QM for you? 

Just asking, since I didn't have a chance to use QMs + k8s, so I am curious about the flow and why did you configure it this way.

2024-11-04 11:38 UTC, antejavor commented on charts/memgraph/values.yaml
> +#   file: ""
We need to fix this so the action can be re-run.

2024-11-05 12:20 UTC, matkob commented on charts/memgraph/values.yaml
> +#   file: ""
Ahh, sorry about that. Added the line

2024-11-05 12:33 UTC, matkob commented
Hi @antejavor, good question! Initially I wanted to create and mount only one ConfigMap with all the custom query modules inside, potentially even stored in multiple files. Unfortunately I bumped into issues related to how Kubernetes mounts the volumes - [it adds timestamp to the mountPath and creates a symlink](https://stackoverflow.com/questions/68331724/kubernetes-volumemount-path-contains-timestamp). This would end up in QM not working in memgraph (they would be duplicated and memgraph wouldn't load the code properly).

Mounting each QM separately, using subPath, fixed the issue and the workaround didn't seem "too dirty" to me. Let me know if this seems sound to you, too :)

2024-11-07 12:28 UTC, antejavor approved these changes
@matkob cool 🚀  thanks a lot for this. 

Let's keep this as a default approach for now, I will take a look at the other options at the future.

2024-11-07 12:28 UTC, merged