add userStorageAccessMode for UserClaim
memgraph/helm-charts pull request #95
Opened 2024-12-10 03:23 UTC by camrossi

This PR would address #94

2024-12-10 08:08 UTC, as51340 approved these changes
Nice work @camrossi! Thanks for the contribution!

2024-12-11 08:39 UTC, antejavor requested changes
Hi @camrossi, thanks a lot for this contribution 🚀  

Before merging, can you update the README that we have on Github for values? https://github.com/memgraph/helm-charts/blob/main/charts/memgraph/README.md#configuration-options 

It describes all configuration options there, after that we can merge!

2024-12-11 21:09 UTC, camrossi commented
@antejavor I added the doc for all the `UserClaim` options as none where present. Also I am wondering if the `userMountPath` shouldn't be set to something as leaving it empty does require the user to manually set it every time

2024-12-12 08:16 UTC, antejavor approved these changes
I think it is ok default, so we can leave it set. 

Looks good to me! 🚀

2025-01-27 13:02 UTC, merged